export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_OUT = 'SIGN_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESSFUL = 'VERIFY_EMAIL_SUCCESSFUL';
export const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED';
