export const UPLOAD_USER_IMAGE = 'UPLOAD_USER_IMAGE';
export const UPLOAD_USER_IMAGE_SUCCESSFUL = 'UPLOAD_USER_IMAGE_SUCCESSFUL';
export const UPLOAD_USER_IMAGE_FAILED = 'UPLOAD_USER_IMAGE_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESSFUL = 'UPDATE_USER_SUCCESSFUL';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
