export const CREATE_DEAL = 'CREATE_DEAL';
export const CREATE_DEAL_SUCCESSFUL = 'CREATE_DEAL_SUCCESSFUL';
export const CREATE_DEAL_FAILED = 'CREATE_DEAL_FAILED';

export const FETCH_DEAL = 'FETCH_DEAL';
export const FETCH_DEAL_SUCCESSFUL = 'FETCH_DEAL_SUCCESSFUL';
export const FETCH_DEAL_FAILED = 'FETCH_DEAL_FAILED';

export const FETCH_DEALS = 'FETCH_DEALS';
export const FETCH_DEALS_SUCCESSFUL = 'FETCH_DEALS_SUCCESSFUL';
export const FETCH_DEALS_FAILED = 'FETCH_DEALS_FAILED';